name: ai_translator
description: "An AI Translator App"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.11+12

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.10.6
  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  dartz: ^0.10.1
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.4
  flutter_svg: ^2.0.16
  flutter_tts: ^4.2.0
  gaimon: ^1.4.0
  get: ^4.6.6
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  just_audio: ^0.9.42
  path: ^1.9.0
  path_provider: ^2.1.5
  popover: ^0.3.1
  provider: ^6.1.2
  pull_down_button: ^0.10.2
  shared_preferences: ^2.3.3
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2
  speech_to_text: ^7.0.0
  flutter_native_splash: ^2.4.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  in_app_review: ^2.0.10
  flutter_email_sender: ^7.0.0
  flutter_app_info: ^3.0.3
  flagsmith: ^6.0.1
  apphud: 2.5.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  string_validator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 24 


flutter_native_splash:
  image: assets/images/icon_cropped.png
  background_image: assets/images/splash.png

flutter:
  uses-material-design: false

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
