name: ai_translator
description: "An AI Translator App"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  gaimon: ^1.3.2
  get: ^4.6.6
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  pull_down_button: ^0.10.2
  shared_preferences: ^2.3.3
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
